install cloog-ppl015
install cmake
install freetype
install gcc47
install gdbm
install git
install gmp4
install gradle
install libpng
install imagemagick
install jpeg
install libmpc08
install libtool
install libyaml
install mpfr2
install mysql
install nkf
install node
install openssl
install ossp-uuid
install pkg-config
install postgresql
install ppl011
install readline
install ruby
install tree
install wget
